name: Dump Global Update

on:
  # schedule:
    # Run every Tuesday at 03:00, 05:00, and 09:00 UTC
    # - cron: '0 3,5,9 * * 2'
    # Run everyday at 07:00 UTC
    # - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dump-global-update:
    environment: "GitHub Action"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
        
      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Get APK & Dumper
        run: python getApkData.py --region global

      - name: Set executable permissions for dumper
        run: |
          chmod +x ./dump_lib/Il2CppInspector/Il2CppInspector
          chmod +x ./dump_lib/FbsDumper/FbsDumper
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run Dumper
        run: python getGlobalVersion.py

      - name: Commit and Push Update
        run: |
          echo "Attempting to commit and push changes..."
          git add global_data/*
          git commit -m "Update Global Data"
          git push