name: Dump JP Update

on:
  # schedule:
    # Run every Tuesday at 03:00, 05:00, and 09:00 UTC
    # - cron: '0 3,5,9 * * 2'
    # Run everyday at 07:00 UTC
    # - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dump-jp-update:
    environment: "GitHub Action"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Get APK & Dumper
        run: python getApkData.py --region jp
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run Dumper
        run: python getJPVersion.py

      - name: Configure Git LFS
        run: |
          git lfs install
          git lfs track "jp_data/**"
          git add .gitattributes
      
      - name: Commit and Push Update
        run: |
          git checkout jp-dump
          git add jp_data/*
          git commit -m "Update JP Data"
          git push origin jp-dump